services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - github-connector
      - github-connector-service
    networks:
      - codeaudit-net

  github-connector:
    image: ${DOCKERHUB_USERNAME}/github-connector:latest
    command: [ "java", "-jar", "app.jar" ]
    container_name: github-connector
    restart: unless-stopped
    environment:
      SERVER_PORT: 8081
      LOG_LEVEL: INFO
    networks:
      - codeaudit-net
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  github-connector-service:
    image: ${DOCKERHUB_USERNAME}/github-connector-service:latest
    command: [ "java", "-jar", "app.jar" ]
    container_name: github-connector-service
    restart: unless-stopped
    environment:
      SERVER_PORT: 8082
      LOG_LEVEL: INFO
      CONNECTOR_URL: http://github-connector:8081
    networks:
      - codeaudit-net
    depends_on:
      github-connector:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  codeaudit-net:
    driver: bridge