services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    image: ${DOCKERHUB_USERNAME}/client:latest
    command: [ "java","-jar","app.jar" ]
    container_name: client
    restart: unless-stopped
    environment:
      SERVER_PORT: 8090
      LOG_LEVEL: INFO
    ports:
      - "8090:8090"
    networks:
      - codeaudit-net
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8090/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    image: ${DOCKERHUB_USERNAME}/gateway:latest
    command: [ "java", "-jar","app.jar" ]
    container_name: gateway
    restart: unless-stopped
    environment:
      SERVER_PORT: 8080
      LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    networks:
      - codeaudit-net
    depends_on:
      client:
        condition: service_healthy
    healthcheck:
      test: [ "CMD","curl","-f","http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  github-connector:
    build:
      context: .
      dockerfile: Dockerfile
      target: github-connector
    image: ${DOCKERHUB_USERNAME}/github-connector:latest
    command: [ "java", "-jar", "app.jar" ]
    container_name: github-connector
    restart: unless-stopped
    environment:
      SERVER_PORT: 8081
      LOG_LEVEL: INFO
    networks:
      - codeaudit-net
    depends_on:
      github-connector-service:
        condition: service_healthy

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  github-connector-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: github-connector-service
    image: ${DOCKERHUB_USERNAME}/github-connector-service:latest
    command: [ "java", "-jar", "app.jar" ]
    container_name: github-connector-service
    restart: unless-stopped
    environment:
      SERVER_PORT: 8082
      LOG_LEVEL: INFO
      CONNECTOR_URL: http://github-connector:8081
    networks:
      - codeaudit-net
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  codeaudit-net:
    driver: bridge