spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://mock/jwks
      client:
        registration: {}
        provider: {}

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration